### ISSUE TITLE
[FEATURE] - save last information and put it as suggestion

### ISSUE THREAD

**Issue by userdehghani** [liara-cloud/desktop#12]
it's so simple but it make new user free from `app` and `port` parameters.
just create new file like `~/.liara-details.json` and save `path`, `app` and `port` like:

```json
{
    "~/Desktop/project-folder": {
        "app": "my-app",
        "port": "5000"
    }
}
```

with this structure we can save deploy information locally and put this information as suggestion in next deploy with `path="~/Desktop/project-folder"`

**Comment by mhemrg** [comment]
Thanks for your suggestion. I've added this to our backlog.
We're gonna close this issue when we have a PR for it.

**Comment by vashian** [comment]
Let me close this issue as the corresponding [PR](https://github.com/liara-cloud/desktop/pull/14) gets merged.
