### ISSUE TITLE
[BUG] - logging out when i disconnect the network, there is no error about connection issue

### ISSUE THREAD

**Issue by userdehghani** [liara-cloud/desktop#13]
![how-it-detect-network-connection-availability](https://user-images.githubusercontent.com/56825715/174481128-ccf02a5a-4dd2-436c-b03e-30b8b241f187.png)

![next-level](https://user-images.githubusercontent.com/56825715/174481208-ea791eda-7ca8-4da3-8b18-9fe8bc8e83ad.png)

**Comment by vashian** [comment]
Thanks 👋 for reporting bugs.
Please feel free to add more information here, Like how we can reproduce this kind of bug.

**Comment by userdehghani** [comment]
it's how to reproduce the bug:

1. deploy a project.
2. turn off wifi.
3. refresh the page or relaunch the app.

**Comment by vashian** [comment]
Hi @userdehghani 

Thank you for bringing this matter to our attention. I wanted to let you know that we've recently merged a new [pull request](https://github.com/liara-cloud/desktop/pull/22) that addresses the connection bugs you mentioned. The changes made have significantly improved the stability of the application.

Please feel free to review the recent changes, and if you have any further questions or feedback, don't hesitate to reach out.
